version: '3.6'
services:

   atlas:
      image: sburn/apache-atlas:2.1.0
      container_name: atlas
      command: /opt/apache-atlas-2.1.0/bin/atlas_start.py
      ports: 
         - 21000:21000
      volumes:
         - ./Entitydefs.json:/tmp/Entitydefs.json
         - ./graffiti_project.json:/tmp/graffiti_project.json
         - ./entities-bulk-atlas.json:/tmp/entities-bulk-atlas.json